kak-ide: add message if unable to start daemon

diff --git a/.local/bin/kak-ide b/.local/bin/kak-ide
--- a/.local/bin/kak-ide
+++ b/.local/bin/kak-ide
@@ -2,10 +2,14 @@
 
 server_name=$(basename `pwd`)
 socket_file=$(kak -l | grep $server_name)
+window_title="Kakoune -"
 
-if [[ $socket_file == "" ]]; then        
-    kak -d -s $server_name &
-    kitty @ set-window-title 'Kakoune - main'
-    kak -c $server_name -e 'ide'
-    kitty @ set-window-title --temporary ''
+if [[ $socket_file == "" ]]; then
+  kak -d -s $server_name &
+  kitty @ set-window-title "$window_title main"
+  kak -c $server_name -e 'ide'
+  kitty @ set-window-title --temporary ''
+else
+  echo "unable to start daemon, socket in use?"
+  exit 1
 fi
