koppa: rewrite of main functionality

diff --git a/.local/bin/koppa b/.local/bin/koppa
--- a/.local/bin/koppa
+++ b/.local/bin/koppa
@@ -1,6 +1,5 @@
 #!/usr/bin/bash
 #
-# 0.1. basic functionality for ls|mk|mv
 # @TODO: throw error when processing file if variable does not exist
 
 xdg_cfg="${XDG_CONFIG_HOME:-$HOME/.config}"
@@ -9,7 +8,6 @@ vars="${xdg_cfg}/koppa/variables.sh"
 
 # used for filename matching
 koppa_id="__"
-ext_regex="(\.[a-zA-Z0-9\-_]{1,20})?"
 # commented code that will change a hidden koppa file to unhidden
 # .file__.ext > file.ext
 unhide_cmd="koppa:unhide"
@@ -20,64 +18,88 @@ tput_blue="$(tput setaf 12)"
 tput_red="$(tput setaf 1)"
 tput_reset="$(tput sgr0)"
 
-# TODO: check files before proceeding
-
 # set shellcheck to avoid these errors
 set -a
+# shellcheck source=/dev/null
 source "$vars"
 set +a
 
-# @args
-# $1 input file path
-write_file() {
-  if [ -f "$1" ]; then
-    # shellcheck disable=2016
-    str_matching='$ENV{$1}'
-    # shellcheck disable=2016
-    str_err='"{ERR~$1}"'
-    # shellcheck disable=2016
-    str_hex='`bash -c "hex_to_rgb $ENV{$1}"`'
-    str_syntax='%\{(\w+)\}%'
-    str_rgb="--rgb"
-    str_syntax_rgb="%\{(\w+)$str_rgb\}%"
-    str_syntax_quoted='"!\{(\w+)\}!"'
-    str_syntax_quoted_rgb="\"!\{(\w+)$str_rgb\}!\""
-    str_code=$(cat "$1")
+hex_to_rgb() {
+  printf "%d, %d, %d" 0x"${1:0:2}" 0x"${1:2:2}" 0x"${1:4:2}"
+}
 
-    # parse %{}% syntax
-    str_code=$(echo "$str_code" | perl -p -e "s/$str_syntax_rgb/(exists $str_matching?$str_hex:$str_err)/eg")
-    str_code=$(echo "$str_code" | perl -p -e "s/$str_syntax/(exists $str_matching?$str_matching:$str_err)/eg")
-
-    # parse "!{}!" syntax
-    str_code=$(echo "$str_code" | perl -p -e "s/$str_syntax_quoted_rgb/(exists $str_matching?$str_hex:$str_err)/eg")
-    str_code=$(echo "$str_code" | perl -p -e "s/$str_syntax_quoted/(exists $str_matching?$str_matching:$str_err)/eg")
-
-    # this both tests for existence of error, and prints
-    if grep 'ERR' <<<"$str_code"; then
-      echo "${tput_red}[ERROR]    $1${tput_reset}"
-      exit 1
-    fi
-
-    # shellcheck disable=2001
-    file_name=$(sed -E "s/(.*)($koppa_id)$ext_regex?$/\1\3/" <<<"$(basename "$1")")
-    if tail "$1" 2>/dev/null | grep -q "$unhide_cmd"; then
-      # shellcheck disable=2001
-      file_name=$(sed 's/^\.//' <<<"$file_name")
-    fi
-    file_out="$(dirname "$1")/$file_name"
-
-    # file needs to be deleted since it's write protected
-    if [ -f "$file_out" ]; then
-      rm -f "$file_out"
-    fi
-
-    echo "$str_code" >>"$file_out"
-    chmod 444 "$file_out"
-    echo "${tput_green}[write]${tput_reset}    $1 -> $file_out"
+check_variable() {
+  if [ -z "${!1+x}" ]; then
+    echo "${tput_red}[ERROR]    $1 is not defined ${tput_reset}" >&2
   fi
 }
 
-parse_files() {
+replace_tokens() {
+  local content="$1"
+  local pattern="$2"
+
+  while [[ $content =~ $pattern ]]; do
+    token="${BASH_REMATCH[1]}"
+
+    if [[ "$token" == *"--rgb" ]]; then
+      base_token="${token//--rgb/}"
+      check_variable "$base_token"
+      rgb_value=$(hex_to_rgb "${!base_token}")
+      content="${content//${BASH_REMATCH[0]}/$rgb_value}"
+    else
+      check_variable "$token"
+      value="${!token}"
+      content="${content//${BASH_REMATCH[0]}/$value}"
+    fi
+  done
+
+  echo "$content"
+}
+
+parse_file() {
+  if [ -f "$1" ]; then
+    file_in=$(basename "$1")
+    base_path=$(dirname "$1")
+    content=$(<"$1")
+
+    # Only if file name ends in "__" or has it before the extension
+    if [[ "$file_in" =~ ^(.+)$koppa_id\.[^.]+$ || "$file_in" =~ ^(.+)$koppa_id$ ]]; then
+      echo "-> $1"
+
+      # Remove the '__' from the file name
+      file_out="${BASH_REMATCH[1]}"
+      if [[ "$file_in" =~ \.[^.]+$ ]]; then
+        extension="${file_in##*.}"
+        file_out="$file_out.$extension"
+      fi
+
+      content=$(<"$1")
+      content=$(replace_tokens "$content" '%\{([^\}]+)\}%')
+      content=$(replace_tokens "$content" '"\!\{([^\}]+)\}\!"')
+
+      # unhide file
+      if tail "$1" 2>/dev/null | grep -q "$unhide_cmd"; then
+        # shellcheck disable=2001
+        file_out=$(sed 's/^\.//' <<<"$file_out")
+      fi
+
+      path_out="$base_path/$file_out"
+
+      # file needs to be deleted since it's write protected
+      if [ -f "$path_out" ]; then
+        rm -f "$path_out"
+      fi
+
+      # write file & prevent writes
+      echo "$content" >"$path_out"
+      chmod 444 "$path_out"
+      echo "${tput_green}[write]${tput_reset}    $1 -> $path_out"
+    fi
+
+  fi
+}
+
+parse_config() {
   # ensure koppa_file is in config
   name=$1
   if ! obj_id=$(jq -e -r ".[] | select(.id==\"${name}\")" "$cfg"); then
@@ -88,25 +110,16 @@ parse_files() {
   # cd into directory and find files
   path=$(echo "$obj_id" | jq -e -r ".path")
   expanded_path=$(eval echo "$path")
-  if [[ -d "$expanded_path" ]]; then
-    # TODO: report error if can't cd
-    cd "$expanded_path" || exit
-
-    # TODO: allow depth setting in config... hardcoding depth for now
-    # find files within directory
-    koppa_files=$(find . -maxdepth 2 -regextype posix-extended -regex ".*${koppa_id}${ext_regex}$")
-
-  else
-    # in this case, a single file is passed TODO: allow multiple files
-    koppa_files=("$expanded_path")
-  fi
-
   echo "${tput_blue}==> $expanded_path${tput_reset}"
 
-  # iterate and parse through files
-  for koppa_file in $koppa_files; do
-    write_file "$koppa_file"
-  done
+  if [[ -d "$expanded_path" ]]; then
+    # iterate and parse through files
+    find "$expanded_path" -type f | while read -r file; do
+      parse_file "$file"
+    done
+  else
+    parse_file "$expanded_path"
+  fi
 
   # support for restarting a service/process
   if cmds=$(echo "$obj_id" | jq -e -r 'try .restart'); then
@@ -131,10 +144,10 @@ ls)
 
   else
     if jq -e ".[] | select(.id==\"$2\")" "$cfg" >/dev/null; then
-      # XXX: using echo seems to excape color output
+      # XXX: using echo seems to escape color output
       jq -e ".[] | select(.id==\"$2\")" "$cfg"
     else
-      echo "\"$2\" is not a key in: $cfg"
+      echo "${tput_red} $2 is not a key in: $cfg ${tput_reset}"
     fi
   fi
   ;;
@@ -142,10 +155,10 @@ mk)
   if [[ "$2" == "all" ]]; then
     all_keys=$(jq -r '.[].id' "$cfg")
     for key in $all_keys; do
-      parse_files "$key"
+      parse_config "$key"
     done
   else
-    parse_files "$2"
+    parse_config "$2"
   fi
   ;;
 *)
