general refactoring

diff --git a/.local/bin/sway-gsettings b/.local/bin/sway-gsettings
--- a/.local/bin/sway-gsettings
+++ b/.local/bin/sway-gsettings
@@ -1,12 +1,19 @@
-#!/bin/bash
-
-# usage: sway-gsettings <settings.ini key>:<gsettings key> <settings.ini key>:<gsettings key>...
+#!/usr/bin/env bash
+#
+# TODO: add ~/.config/gtk-3.0/sway-mappings.ini to allow control
+# of which settings to 'set' from a config file.
 
 config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
-[[ ! -f "$config" ]] && exit 1
 
-call_gsettings() {
+if [[ ! -f "$config" ]]; then
+  echo "File not found: $config"
+  exit 1
+fi
+
+gsettings_set() {
   for pair in "$@"; do
+    # store command and execute using awk's system()
+    # cmd: gsettings set org.gnome.desktop.interface key-name "value"
     IFS=':' read -r -a NAMES <<< $pair
     exp="$exp /^${NAMES[0]}/{
       cmd=sprintf(\"gsettings set org.gnome.desktop.interface %s \\\"%s\\\"\\n\",
@@ -18,7 +25,8 @@ call_gsettings() {
   awk -F' +?= +?' "$exp" "$config"
 }
 
-call_gsettings \
+# XXX: hardcoded, use config file for mappings
+gsettings_set \
   gtk-theme-name:gtk-theme \
   gtk-icon-theme-name:icon-theme \
   gtk-font-name:font-name
