sway-gammastep: refactor

diff --git a/.local/bin/sway-gammastep b/.local/bin/sway-gammastep
--- a/.local/bin/sway-gammastep
+++ b/.local/bin/sway-gammastep
@@ -1,68 +1,62 @@
 #!/bin/bash
+#
 
-status="$(systemctl --user status gammastep.service | awk '
-  BEGIN{ FS=": " }
-  /Active: (in)?active /{
-    print gensub(/^((in)?active) .*/, "\\1", "G", $2)
-  }
-')"
+INACTIVE=inactive
+FS=": "
 
-# gets current mode based on location -- this is irrespective of service running
-modeline=$(gammastep -p 2>&1 | sed 's/Notice: //g' | awk 'BEGIN{ ORS="|" }1')
+status=$(systemctl --user is-active gammastep.service)
+modeline=$(gammastep -p 2>&1 | sed 's/Notice: //g')
 
-# TODO: should be able to pass variable to awk, not pipe
-period="$(echo $modeline | awk '
-  BEGIN{ RS="|"; FS=": " }
+period=$(echo "$modeline" | awk -F "$FS" '
   /^Period: Transition/{
-    dig=gensub(/Transition \(([0-9])[0-9]?\.[0-9][0-9]?% day\)/, "\\1", "G", $2);
-    if (dig < 5) print "TransitionNight"
-    else print "TransitionDay"
+    dig=gensub(/Transition.*([0-9]i)[0-9]?\.[0-9][0-9]?%.*/, "\\1", "G", $2);
+    if (dig < 5) print "Transition Night"
+    else print "Transition Day"
     exit
   }
   /^Period/{ print $2}
-')"
+')
 
 # TODO: need update module (use signal?)
 toggle_service () {
-  if [ "$status" = "inactive" ]; then
+  if [[ "$status" == "$INACTIVE" ]]; then
     systemctl --user start gammastep.service
   else
     systemctl --user stop gammastep.service
   fi
-  exit 1
 }
 
 status_waybar () {
-  tooltip="$(echo $modeline | awk '
-    BEGIN{ FS=": "; RS="|"; ORS=""; OFS=""}
+  tooltip=$(echo "$modeline" | awk -F "$FS" '
     /^Location/{
-      gsub(",", " -")
-      print gensub(/([0-9]{2}\.[0-9]{2}) (N|W|S|E)/, "\\2:\\1", "G", $2), " | ";
-      next
+      printf " %s   ", $2
     }
-    /^Period/{ next }
-    { if(NR < 5) print $2; if (NR < 4) print " | " }
-  ')"
+    /^Solar elevation/{
+      printf " %s ", $2
+    }
+  ')
+
+  tooltip="$tooltip ($period)"
 
   case $period in
-  Daytime)
-    percentage="0";;
-  TransitionDay)
-    percentage="34";;
-  TransitionNight)
-    percentage="67";;
-  Night)
-    percentage="100";;
-  *)
-    echo "Unable to parse gammastep period to percentage"
-    exit 1;;
+    Daytime)
+      percentage="0";;
+    "Transition Day")
+      percentage="34";;
+    "Transition Night")
+      percentage="67";;
+    Night)
+      percentage="100";;
+    *)
+      echo "Unable to parse gammastep period to percentage"
+      exit 1;;
   esac
 
   echo "{\"percentage\":$percentage,\"tooltip\":\"$tooltip\",\"class\":\"$status\"}"
 }
 
 colorscheme_kak () {
-  if [ "$period" = "Night" ]; then
+  if [[ "$period" =~ Night$ ]]; then
     variant="dark"
   else
     variant="light"
@@ -79,6 +73,9 @@ case "$1" in
   kak)
     colorscheme_kak;;
   *)
-    echo "Usage: waystep {toogle|waybar|kak}"
+    echo -e "Usage: $(basename $0) {toogle|waybar|kak}\n"
+    echo -e "toggle\t\t print systemd service"
+    echo -e "waybar\t\t print waybar json data"
+    echo -e "kak\t\t theme variant"
     exit 1;;
 esac
