waybar-updates: provide better config/formatting, separate software from firmware

diff --git a/.local/bin/waybar-updates b/.local/bin/waybar-updates
--- a/.local/bin/waybar-updates
+++ b/.local/bin/waybar-updates
@@ -5,47 +5,82 @@ status=
 # get update info on one line w/ ''\n'
 awk_escape_nl='{ printf "\t%s\\n", $0 }'
 
-# pacman
-pac=$(checkupdates)
-# NOTE: NF (number of fields) is empty for blank lines
-# awks default behavior is to print line, so only non-blank are printed
-pac_count=$(echo "$pac" | awk NF | wc -l)
-pac_info=$(echo "$pac" | awk "$awk_escape_nl")
+case "$1" in
+  software)
+    # pacman
+    pac=$(checkupdates)
+    # NOTE: NF (number of fields) is empty for blank lines
+    # awks default behavior is to print line, so only non-blank are printed
+    pac_count=$(echo "$pac" | awk NF | wc -l)
+    pac_info=$(echo "$pac" | awk "$awk_escape_nl")
 
-# aur
-aur=$(yay -Qua)
-aur_count=$(echo "$aur" | awk NF | wc -l)
-aur_info=$(echo "$aur" | awk "$awk_escape_nl")
+    # aur
+    aur=$(aur repo -d paks --list | aur vercmp)
+    aur_count=$(echo "$aur" | awk NF | wc -l)
+    aur_info=$(echo "$aur" | awk "$awk_escape_nl")
 
-# fwupd (lenovo)
-fwupd_jq_simplify=".Devices[] | { dev: .Name, count: (.Releases|length|tostring), updates: [.Releases[] | {name: .Summary, ver: .Version, desc: .Description}] }"
-fwupd_jq_unique=".updates[].ver"
-fwupd_jq_finalout='.count+" "+.dev, (.updates[]|"   - "+.ver+": "+.name)'
+    # svr
+    svr=$(ssh svr checkupdates)
+    svr_count=$(echo "$svr" | awk NF | wc -l)
+    svr_info=$(echo "$svr" | awk "$awk_escape_nl")
 
-fwupd=$(fwupdmgr get-updates --json | jq "$fwupd_jq_simplify" 2> /dev/null)
-fwupd_count=$(echo "$fwupd" | jq "$fwupd_jq_unique" | awk NF | wc -l)
-fwupd_info=$(echo "$fwupd" | jq --raw-output "$fwupd_jq_finalout" | awk "$awk_escape_nl")
+    # set status icons & tooltip
+    if ((svr_count == 0 && pac_count == 0 && aur_count == 0)); then
+      tooltip+="Up to date"
+      alt="uptodate"
 
-# set status icons & tooltip
-if ((pac_count == 0 && aur_count == 0 && fwupd_count == 0)); then
-  status+=""
-  tooltip+="Up to date"
+    else
+      alt="pac"
 
-else
-  if ((pac_count > 0 || aur_count > 0)); then
-    ((aur_count > 0)) && status+="*"
-    status+=""
-  fi
-  ((fwupd_count > 0)) && status+=" "
+      if ((aur_count == 0 && svr_count == 0)); then
+        alt+="_only"
+      else
+        if ((aur_count > 0)); then
+          alt+="_aur"
+        fi
+        if ((svr_count > 0)); then
+          alt+="_svr"
+        fi
+      fi
 
-  # print info for tooltip
-  ((fwupd_count > 0)) && tooltip+="(${fwupd_count}) firmware:\n${fwupd_info}\n"
-  ((aur_count > 0)) && tooltip+="(${aur_count}) aur:\n${aur_info}\n"
-  ((pac_count > 0)) && tooltip+="(${pac_count}) pacman:\n${pac_info}\n"
+      # print info for tooltip
+      ((svr_count > 0)) && tooltip+="(${svr_count}) svr:\n${svr_info}\n"
+      ((aur_count > 0)) && tooltip+="(${aur_count}) aur:\n${aur_info}\n"
+      ((pac_count > 0)) && tooltip+="(${pac_count}) pacman:\n${pac_info}\n"
 
-  tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
+      tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
 
-fi
+    fi
 
-# write obj for waybar
-[[ "$status" ]] && echo "{\"text\": \"$status\",\"tooltip\":\"$tooltip\"}"
+    # write obj for waybar
+    echo "{\"tooltip\":\"$tooltip\",\"alt\":\"$alt\"}"
+    ;;
+  firmware)
+    # fwupd (lenovo)
+    fwupd_jq_simplify=".Devices[] | { dev: .Name, count: (.Releases|length|tostring), updates: [.Releases[] | {name: .Summary, ver: .Version, desc: .Description}] }"
+    fwupd_jq_unique=".updates[].ver"
+    fwupd_jq_finalout='.count+" "+.dev, (.updates[]|"   - "+.ver+": "+.name)'
+
+    fwupd=$(fwupdmgr get-updates -y --json | jq "$fwupd_jq_simplify" 2> /dev/null)
+    fwupd_count=$(echo "$fwupd" | jq "$fwupd_jq_unique" | awk NF | wc -l)
+    fwupd_info=$(echo "$fwupd" | jq --raw-output "$fwupd_jq_finalout" | awk "$awk_escape_nl")
+
+    # set status icons & tooltip
+    if ((fwupd_count == 0)); then
+      tooltip+="Up to date"
+      alt="uptodate"
+
+    else
+      alt="outdated"
+      tooltip+="(${fwupd_count}) firmware:\n${fwupd_info}\n"
+      tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
+    fi
+
+    # write obj for waybar
+    echo "{\"tooltip\":\"$tooltip\",\"alt\":\"$alt\"}"
+    ;;
+  *)
+    echo >&2 "Invalid option"
+    exit 1
+    ;;
+esac
