waybar: updates/firmware use cache file, fixes for pomodoro/x1profile

diff --git a/.local/bin/waybar-updates b/.local/bin/waybar-updates
--- a/.local/bin/waybar-updates
+++ b/.local/bin/waybar-updates
@@ -1,90 +1,138 @@
 #!/usr/bin/env bash
 
-# icons to be displayed
-status=
+software_cache="${XDG_CACHE_HOME:-$HOME/.cache}/waybar-updates.software"
+firmware_cache="${XDG_CACHE_HOME:-$HOME/.cache}/waybar-updates.firmware"
+
 # get update info on one line w/ ''\n'
 awk_escape_nl='{ printf "\t%s\\n", $0 }'
+# preserve newlines in command arguments
+IFS=
+
+get_count() {
+  echo "$1" | wc -l
+}
+
+get_details() {
+  max=15
+  count=$(get_count "$1")
+  list="$1"
+  ((count > max)) && list=$(echo "$1" | head -n $max) && list+="\n..."
+  echo -e "$list" | awk "$awk_escape_nl"
+}
+
+get_waybar_data() {
+  if [ -f "$1" ]; then
+    cat "$1"
+  else
+    printf '{"tooltip": "%s is missing", "alt": "error"}' "$1"
+  fi
+}
+
+print_usage() {
+  echo >&2 "Usage: $0 <refresh|display> <software|firmware>"
+  exit 1
+}
 
 case "$1" in
-  software)
-    # pacman
-    pac=$(checkupdates)
-    # NOTE: NF (number of fields) is empty for blank lines
-    # awks default behavior is to print line, so only non-blank are printed
-    pac_count=$(echo "$pac" | awk NF | wc -l)
-    pac_info=$(echo "$pac" | awk "$awk_escape_nl")
-
-    # aur
-    if aur repo -d paks &> /dev/null; then
-      aur=$(aur repo -d paks --list | aur vercmp)
-      aur_count=$(echo "$aur" | awk NF | wc -l)
-      aur_info=$(echo "$aur" | awk "$awk_escape_nl")
-    fi
-
-    # svr
-    if grep svr ~/.ssh/config -q; then
-      svr=$(ssh svr checkupdates)
-      svr_count=$(echo "$svr" | awk NF | wc -l)
-      svr_info=$(echo "$svr" | awk "$awk_escape_nl")
-    fi
-
-    # set status icons & tooltip
-    if ((svr_count == 0 && pac_count == 0 && aur_count == 0)); then
-      tooltip+="Up to date"
-      alt="uptodate"
-
-    else
-      alt="pac"
-
-      if ((aur_count == 0 && svr_count == 0)); then
-        alt+="_only"
-      else
-        if ((aur_count > 0)); then
-          alt+="_aur"
-        fi
-        if ((svr_count > 0)); then
-          alt+="_svr"
-        fi
-      fi
-
-      # print info for tooltip
-      ((svr_count > 0)) && tooltip+="(${svr_count}) svr:\n${svr_info}\n"
-      ((aur_count > 0)) && tooltip+="(${aur_count}) aur:\n${aur_info}\n"
-      ((pac_count > 0)) && tooltip+="(${pac_count}) pacman:\n${pac_info}\n"
-
-      tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
-
-    fi
-
-    # write obj for waybar
-    echo "{\"tooltip\":\"$tooltip\",\"alt\":\"$alt\"}"
+  display)
+    case "$2" in
+      software)
+        get_waybar_data "$software_cache"
+        ;;
+      firmware)
+        get_waybar_data "$firmware_cache"
+        ;;
+      *)
+        print_usage
+        ;;
+    esac
     ;;
-  firmware)
-    # fwupd (lenovo)
-    fwupd_jq_simplify=".Devices[] | { dev: .Name, count: (.Releases|length|tostring), updates: [.Releases[] | {name: .Summary, ver: .Version, desc: .Description}] }"
-    fwupd_jq_unique=".updates[].ver"
-    fwupd_jq_finalout='.count+" "+.dev, (.updates[]|"   - "+.ver+": "+.name)'
+  refresh)
+    case "$2" in
+      software)
+        # pacman
+        pac=$(checkupdates)
+        pac_count=$(get_count "$pac")
+        pac_info=$(get_details "$pac")
 
-    fwupd=$(fwupdmgr get-updates -y --json | jq "$fwupd_jq_simplify" 2> /dev/null)
-    fwupd_count=$(echo "$fwupd" | jq "$fwupd_jq_unique" | awk NF | wc -l)
-    fwupd_info=$(echo "$fwupd" | jq --raw-output "$fwupd_jq_finalout" | awk "$awk_escape_nl")
+        # aur
+        if aur repo -d paks &> /dev/null; then
+          aur=$(aur repo -d paks --list | aur vercmp)
+          aur_count=$(get_count "$aur")
+          aur_info=$(get_details "$aur")
+        fi
 
-    # set status icons & tooltip
-    if ((fwupd_count == 0)); then
-      tooltip+="Up to date"
-      alt="uptodate"
+        # svr
+        if grep svr ~/.ssh/config -q; then
+          svr=$(ssh svr checkupdates)
+          svr_count=$(get_count "$svr")
+          svr_info=$(get_details "$svr")
+        fi
 
-    else
-      alt="outdated"
-      tooltip+="(${fwupd_count}) firmware:\n${fwupd_info}\n"
-      tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
-    fi
+        # set status icons & tooltip
+        if ((svr_count == 0 && pac_count == 0 && aur_count == 0)); then
+          tooltip+="Up to date"
+          alt="uptodate"
 
-    # write obj for waybar
-    echo "{\"tooltip\":\"$tooltip\",\"alt\":\"$alt\"}"
+        else
+          if ((pac_count > 0)); then
+            alt="pac"
+          else
+            alt="nopac"
+          fi
+
+          if ((aur_count > 0)); then
+            alt+="_aur"
+          fi
+          if ((svr_count > 0)); then
+            alt+="_svr"
+          fi
+
+          # print info for tooltip
+          ((svr_count > 0)) && tooltip+="(${svr_count}) svr:\n${svr_info}\n"
+          ((aur_count > 0)) && tooltip+="(${aur_count}) aur:\n${aur_info}\n"
+          ((pac_count > 0)) && tooltip+="(${pac_count}) pac:\n${pac_info}\n"
+
+          tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
+
+        fi
+
+        # write obj for waybar
+        printf '{"tooltip": "%s", "alt": "%s"}' "$tooltip" "$alt" > "$software_cache"
+        ;;
+      firmware)
+        fwupdmgr refresh 2> /dev/null
+
+        fwupd_jq_simplify=".Devices[] | { dev: .Name, count: (.Releases|length|tostring), updates: [.Releases[] | {name: .Summary, ver: .Version, desc: .Description}] }"
+        fwupd_jq_unique=".updates[].ver"
+        fwupd_jq_finalout='.count+" "+.dev, (.updates[]|"   - "+.ver+": "+.name)'
+
+        fwupd_raw=$(fwupdmgr get-updates -y --json | jq "$fwupd_jq_simplify" 2> /dev/null)
+        fwupd_unique=$(echo "$fwupd_raw" | jq "$fwupd_jq_unique")
+        fwupd_json=$(echo "$fwupd_raw" | jq --raw-output "$fwupd_jq_finalout")
+        fwupd_count=$(get_count "$fwupd_unique")
+        fwupd_info=$(get_count "$fwupd_json")
+
+        # set status icons & tooltip
+        if ((fwupd_count == 0)); then
+          tooltip+="Up to date"
+          alt="uptodate"
+
+        else
+          alt="outdated"
+          tooltip+="(${fwupd_count}) firmware:\n${fwupd_info}\n"
+          tooltip=$(echo -n "$tooltip" | sed 's/\\n\\n$/\\n/')
+        fi
+
+        # write obj for waybar
+        printf '{"tooltip": "%s", "alt": "%s"}' "$tooltip" "$alt" > "$firmware_cache"
+        ;;
+      *)
+        print_usage
+        ;;
+    esac
     ;;
   *)
-    echo >&2 "Invalid option"
-    exit 1
+    print_usage
     ;;
 esac
